"use client";
import Link from "next/link";
import { useEffect,useState } from "react";

type Kpis={customers:number;activeDomains:number;orders30d:number;openTickets:number;disputedPayments:number;failedLogins24h:number;suspendedCustomers:number};
type Data={generatedAt:string;viewer:{id:string;role:string};kpis:Kpis;finance30d:{grossCents:number;refundedCents:number;feesCents:number;netCents:number}|null;recurring:{pastDue:number;renewalInvoices:number}|null;websites:{customDomains:number;failedDomains:number}|null;services:Array<{provider_name:string;status:string;count:number}>;queues:{provisioningFailures:any[];paymentQueue:any[];supportQueue:any[]};riskSignals:{failedLogins24h:number;suspendedCustomers:number;disputedPayments:number;highValueOrders:any[]};providers:any[];staff:any[];recentAudit:any[]};
const ROLES=["SUPER_ADMIN","ADMIN","SUPPORT","FINANCE","CONTENT_MANAGER","PRODUCT_MANAGER"];
const money=(c:number)=>new Intl.NumberFormat(undefined,{style:"currency",currency:"USD"}).format(c/100);
export default function ControlCenter(){const[data,setData]=useState<Data|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
async function load(){setLoading(true);try{const r=await fetch("/api/admin/control-center",{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to load control center.");setData(b.data??b);setError("");}catch(e){setError(e instanceof Error?e.message:"Unable to load control center.");}finally{setLoading(false);}}
useEffect(()=>{void load();},[]);
async function changeRole(id:string,role:string){if(!window.confirm(`Change this staff account to ${role}?`))return;const r=await fetch(`/api/admin/staff/${id}/role`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({role})});const b=await r.json();if(!r.ok){setError(b.error||"Role change failed.");return;}await load();}
if(!data&&loading)return <p className="text-sm text-ink/60">Loading control center…</p>;if(!data)return <div className="card p-6 text-danger">{error}</div>;
const alertCount=data.kpis.openTickets+data.kpis.disputedPayments+(data.recurring?.pastDue||0)+data.queues.provisioningFailures.length;
return <main className="space-y-8"><header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-medium">Administration</p><h1 className="text-3xl font-bold">Control Center</h1><p className="mt-2 max-w-3xl text-sm text-ink/55">One operational view across customers, commerce, providers, fulfilment, support, risk, staff access and audit activity.</p></div><button className="btn-secondary" disabled={loading} onClick={()=>void load()}>{loading?"Refreshing…":"Refresh"}</button></header>{error&&<div className="rounded-xl border border-danger/20 bg-danger/5 p-4 text-sm text-danger">{error}</div>}
<section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><K label="Customers" value={data.kpis.customers}/><K label="Active domains" value={data.kpis.activeDomains}/><K label="Orders · 30 days" value={data.kpis.orders30d}/><K label="Attention signals" value={alertCount} warn={alertCount>0}/>{data.finance30d&&<><K label="Gross captured · 30d" value={money(data.finance30d.grossCents)}/><K label="Refunded · 30d" value={money(data.finance30d.refundedCents)}/><K label="Provider fees · 30d" value={money(data.finance30d.feesCents)}/><K label="Net settlement · 30d" value={money(data.finance30d.netCents)}/></>}</section>
<section><h2 className="text-xl font-bold">Action queues</h2><div className="mt-3 grid gap-4 xl:grid-cols-3"><Queue title="Provisioning failures" href="/admin/orders" rows={data.queues.provisioningFailures.map(x=>({a:x.order.orderNumber,b:x.description,c:x.provisioningNote||"Provisioning failed"}))}/><Queue title="Payments requiring attention" href="/admin/payments" rows={data.queues.paymentQueue.map(x=>({a:x.order.orderNumber,b:`${money(x.amountCents)} · ${x.status}`,c:x.failureReason||x.order.user.email}))}/><Queue title="Support queue" href="/admin/support" rows={data.queues.supportQueue.map(x=>({a:x.subject,b:`${x.priority} · ${x.status}`,c:x.user.email}))}/></div></section>
<section className="grid gap-5 xl:grid-cols-2"><div className="card p-5"><div className="flex justify-between"><h2 className="font-bold">Provider & service health</h2><Link href="/admin/providers" className="text-sm font-semibold text-brand-600">Providers</Link></div><div className="mt-4 space-y-2">{data.providers.map(p=><div key={p.provider} className="flex items-center justify-between rounded-lg border border-border p-3 text-sm"><div><strong>{p.provider}</strong><p className="text-xs text-ink/45">{p.lastTestMessage||"Not live-tested"}</p></div><span className={p.lastTestOk?"badge-success":"badge-neutral"}>{p.lastTestOk?"Verified":p.isConfigured?"Needs test":"Not configured"}</span></div>)}</div><div className="mt-4 grid grid-cols-2 gap-2">{data.services.map(s=><div key={`${s.provider_name}-${s.status}`} className="rounded-lg bg-ink/5 p-3 text-sm"><strong>{s.count}</strong> {s.provider_name}<p className="text-xs text-ink/45">{s.status}</p></div>)}</div></div>
<div className="card p-5"><h2 className="font-bold">Risk signals</h2><div className="mt-4 grid grid-cols-3 gap-2"><K label="Failed logins · 24h" value={data.riskSignals.failedLogins24h} warn={data.riskSignals.failedLogins24h>20}/><K label="Suspended customers" value={data.riskSignals.suspendedCustomers} warn={data.riskSignals.suspendedCustomers>0}/><K label="Disputes" value={data.riskSignals.disputedPayments} warn={data.riskSignals.disputedPayments>0}/></div><h3 className="mt-5 text-sm font-bold">High-value orders · 30 days</h3><div className="mt-2 space-y-2">{data.riskSignals.highValueOrders.map(o=><Link key={o.id} href={`/admin/orders/${o.id}`} className="block rounded-lg border border-border p-3 text-sm hover:bg-ink/5"><strong>{o.orderNumber}</strong> · {money(o.totalCents)}<p className="text-xs text-ink/45">{o.user.email} · {o.status}</p></Link>)}{!data.riskSignals.highValueOrders.length&&<p className="text-sm text-ink/50">No high-value orders in this window.</p>}</div></div></section>
<section className="card p-5"><div className="flex flex-wrap justify-between gap-2"><div><h2 className="font-bold">Staff access</h2><p className="text-xs text-ink/50">Role changes require Super Admin. MFA status is visible so privileged access can be hardened before production.</p></div><span className="badge-neutral">Your role: {data.viewer.role}</span></div><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-3">Staff</th><th className="p-3">Role</th><th className="p-3">MFA</th><th className="p-3">Account</th></tr></thead><tbody>{data.staff.map(s=><tr key={s.id} className="border-b last:border-0"><td className="p-3"><strong>{s.firstName} {s.lastName}</strong><p className="text-xs text-ink/45">{s.email}</p></td><td className="p-3">{data.viewer.role==="SUPER_ADMIN"?<select className="input max-w-52" value={s.adminRole||""} onChange={e=>void changeRole(s.id,e.target.value)}>{ROLES.map(r=><option key={r}>{r}</option>)}</select>:s.adminRole}</td><td className="p-3"><span className={s.mfaEnabled?"badge-success":"badge-warning"}>{s.mfaEnabled?"Enabled":"Required"}</span></td><td className="p-3"><span className={s.isSuspended?"badge-danger":"badge-success"}>{s.isSuspended?"Suspended":"Active"}</span></td></tr>)}</tbody></table></div></section>
<section className="card p-5"><h2 className="font-bold">Recent audit trail</h2><div className="mt-3 divide-y divide-border">{data.recentAudit.slice(0,20).map(a=><div key={a.id} className="py-3 text-sm"><div className="flex justify-between gap-3"><strong>{a.action}</strong><span className="text-xs text-ink/45">{new Date(a.createdAt).toLocaleString()}</span></div><p className="text-xs text-ink/45">{a.resource}{a.resourceId?` · ${a.resourceId}`:""}</p></div>)}</div></section></main>}
function K({label,value,warn=false}:{label:string;value:string|number;warn?:boolean}){return <div className={`rounded-xl border p-4 ${warn?"border-amber-300 bg-amber-50":"border-border"}`}><p className="text-xs text-ink/50">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></div>}
function Queue({title,href,rows}:{title:string;href:string;rows:Array<{a:string;b:string;c:string}>}){return <div className="card p-5"><div className="flex justify-between"><h3 className="font-bold">{title}</h3><Link href={href} className="text-xs font-semibold text-brand-600">Open queue</Link></div><div className="mt-3 space-y-2">{rows.slice(0,8).map((r,i)=><div key={`${r.a}-${i}`} className="rounded-lg border border-border p-3 text-sm"><strong>{r.a}</strong><p>{r.b}</p><p className="text-xs text-ink/45">{r.c}</p></div>)}{!rows.length&&<p className="text-sm text-ink/50">No items waiting.</p>}</div></div>}
