import { NextRequest } from "next/server";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { jsonError,jsonOk,handleError } from "@/lib/api";
import { ensureSupportSla,resolveOperationalAlert } from "@/lib/messaging";
import { logAudit } from "@/lib/audit";
type Ctx={params:Promise<{id:string}>};
export async function GET(_req:NextRequest,{params}:Ctx){try{await requireAdmin();const{id}=await params;const ticket=await prisma.supportTicket.findUnique({where:{id},include:{messages:{orderBy:{createdAt:"asc"}},user:{select:{email:true,firstName:true,lastName:true}}}});if(!ticket)return jsonError("Ticket not found.",404);const ops=await prisma.$queryRaw<Array<{sla_due_at:Date|null;escalated_at:Date|null;escalation_reason:string|null;last_staff_reply_at:Date|null;last_customer_reply_at:Date|null}>>`SELECT "sla_due_at","escalated_at","escalation_reason","last_staff_reply_at","last_customer_reply_at" FROM "support_ticket_ops" WHERE "ticket_id"=${id} LIMIT 1`;return jsonOk({ticket,ops:ops[0]??null});}catch(error){return handleError(error);}}
const schema=z.object({status:z.enum(["OPEN","PENDING","RESOLVED","CLOSED"]).optional(),priority:z.enum(["LOW","NORMAL","HIGH","URGENT"]).optional(),assignedTo:z.string().nullable().optional()});
export async function PATCH(req:NextRequest,{params}:Ctx){try{const admin=await requireAdmin(["SUPER_ADMIN","ADMIN","SUPPORT"]);const{id}=await params;const input=schema.parse(await req.json());if(input.assignedTo){const staff=await prisma.user.findFirst({where:{id:input.assignedTo,adminRole:{not:null},isSuspended:false},select:{id:true}});if(!staff)return jsonError("Assigned staff account is not active.",422);}const ticket=await prisma.supportTicket.update({where:{id},data:input});if(input.priority)await ensureSupportSla(id,input.priority);if(input.status&&["RESOLVED","CLOSED"].includes(input.status)){await resolveOperationalAlert(`support-sla:${id}`);await resolveOperationalAlert(`support-reply:${id}`);await resolveOperationalAlert(`support-urgent:${id}`);}await logAudit({actorId:admin.id,action:"support.ticket_updated",resource:"support_ticket",resourceId:ticket.id,metadata:input});return jsonOk({ticket});}catch(error){return handleError(error);}}
