"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
type Data={alerts:any[];deliveries:any[];webhooks:any[];sla:any[]};
export default function MessagingOps(){const[data,setData]=useState<Data|null>(null);const[busy,setBusy]=useState("");const[error,setError]=useState("");async function load(){const r=await fetch("/api/admin/messaging",{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to load messaging operations.");setData(b);}useEffect(()=>{load().catch(e=>setError(e.message));},[]);async function action(body:any){setBusy(body.id);try{const r=await fetch("/api/admin/messaging",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const b=await r.json();if(!r.ok)throw new Error(b.error||"Action failed.");await load();}catch(e){setError(e instanceof Error?e.message:"Action failed.");}finally{setBusy("");}}
if(!data)return <p className="text-sm text-ink/60">Loading messaging operations…</p>;return <main className="space-y-8"><header><p className="text-sm font-medium">Operations</p><h1 className="text-3xl font-bold">Messaging & Alerts</h1><p className="mt-2 max-w-3xl text-sm text-ink/55">Transactional delivery evidence, support SLA escalation and inbound provider webhook health. Customer/developer webhook subscriptions are intentionally reserved for Phase 23.</p></header>{error&&<div className="rounded-xl border border-danger/20 bg-danger/5 p-4 text-sm text-danger">{error}</div>}
<section><h2 className="text-xl font-bold">Open operational alerts</h2><div className="mt-3 space-y-3">{data.alerts.map(a=><div key={a.id} className="card p-4"><div className="flex flex-wrap justify-between gap-3"><div><div className="flex items-center gap-2"><span className={a.severity==="CRITICAL"?"badge-danger":a.severity==="WARNING"?"badge-warning":"badge-neutral"}>{a.severity}</span><strong>{a.title}</strong></div><p className="mt-2 text-sm text-ink/60">{a.body}</p><p className="mt-1 text-xs text-ink/40">{a.source} · {a.resource_type||"system"}{a.resource_id?` · ${a.resource_id}`:""}</p></div><div className="flex gap-2"><button className="btn-secondary" disabled={busy!==""} onClick={()=>void action({action:"ALERT_STATUS",id:a.id,status:"ACKNOWLEDGED"})}>Acknowledge</button><button className="btn-primary" disabled={busy!==""} onClick={()=>void action({action:"ALERT_STATUS",id:a.id,status:"RESOLVED"})}>Resolve</button></div></div></div>)}{!data.alerts.length&&<div className="card p-5 text-sm text-ink/50">No open operational alerts.</div>}</div></section>
<section className="grid gap-5 xl:grid-cols-2"><div className="card p-5"><h2 className="font-bold">Transactional delivery</h2><div className="mt-3 max-h-[520px] space-y-2 overflow-y-auto">{data.deliveries.map(d=><div key={d.id} className="rounded-lg border border-border p-3 text-sm"><div className="flex justify-between gap-3"><div><strong>{d.template_key}</strong><p className="text-xs text-ink/45">{d.channel} · {d.recipient||"in-app"} · attempts {d.attempts}</p></div><span className={d.status==="SENT"?"badge-success":d.status==="FAILED"?"badge-danger":"badge-neutral"}>{d.status}</span></div>{d.error_message&&<p className="mt-2 text-xs text-danger">{d.error_message}</p>}{d.channel==="EMAIL"&&d.status!=="SENT"&&d.status!=="SKIPPED"&&<button className="btn-secondary mt-2" disabled={busy!==""} onClick={()=>void action({action:"RETRY_DELIVERY",id:d.id})}>Retry now</button>}</div>)}</div></div>
<div className="card p-5"><div className="flex justify-between"><h2 className="font-bold">Support SLA</h2><Link href="/admin/support" className="text-xs font-semibold text-brand-600">Support queue</Link></div><div className="mt-3 space-y-2">{data.sla.map(s=><Link key={s.ticket_id} href={`/admin/support/${s.ticket_id}`} className="block rounded-lg border border-border p-3 text-sm hover:bg-ink/5"><div className="flex justify-between gap-2"><strong>{s.subject}</strong><span className={s.escalated_at?"badge-danger":"badge-neutral"}>{s.escalated_at?"Escalated":s.priority}</span></div><p className="mt-1 text-xs text-ink/45">SLA due {s.sla_due_at?new Date(s.sla_due_at).toLocaleString():"not set"}{s.assignedTo?` · assigned ${s.assignedTo}`:""}</p></Link>)}</div></div></section>
<section className="card p-5"><h2 className="font-bold">Inbound provider webhook events</h2><p className="mt-1 text-xs text-ink/50">This is processing health for provider webhooks already used by GetSawa. Outbound developer subscriptions belong to Phase 23.</p><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-3">Provider</th><th className="p-3">Event</th><th className="p-3">Received</th><th className="p-3">Processing</th></tr></thead><tbody>{data.webhooks.map(w=><tr key={w.id} className="border-b last:border-0"><td className="p-3">{w.provider}</td><td className="p-3">{w.eventType}</td><td className="p-3">{new Date(w.receivedAt).toLocaleString()}</td><td className="p-3"><span className={w.processingStatus==="PROCESSED"?"badge-success":w.processingStatus==="FAILED"?"badge-danger":"badge-neutral"}>{w.processingStatus}</span>{w.errorMessage&&<p className="mt-1 max-w-md text-xs text-danger">{w.errorMessage}</p>}</td></tr>)}</tbody></table></div></section></main>}
