"use client";
import { useEffect,useState } from "react";
import Link from "next/link";

type Service={service_instance_id:string;service_status:string;product_name:string;domain_name:string;zone_status:string;assigned_nameservers:string[];dns_migration_status:string;dns_unsupported:unknown[];cutover_status:string;proxy_enabled:boolean;https_enforced:boolean;dnssec_status:string;billing_status:string|null;current_period_end:string|null;auto_renew:boolean|null};
type RecordRow={id:string;type:string;name:string;content:string;ttl:number;proxied:boolean;priority?:number};
export default function SecurityPage(){const[data,setData]=useState<{provider:{verified:boolean;reason:string|null};services:Service[]}|null>(null);const[records,setRecords]=useState<Record<string,RecordRow[]>>({});const[busy,setBusy]=useState("");const[error,setError]=useState("");const[form,setForm]=useState({serviceId:"",type:"A",name:"@",content:"",priority:""});
async function load(){setError("");const r=await fetch("/api/dashboard/security",{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to load security services.");setData(b.data??b);}useEffect(()=>{load().catch(e=>setError(e.message));},[]);
async function loadDns(id:string){const r=await fetch(`/api/dashboard/security/${id}/dns`,{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to load DNS.");setRecords(v=>({...v,[id]:(b.data??b).records||[]}));}
async function action(id:string,path:string,method="POST",body?:unknown){setBusy(`${id}:${path}`);setError("");try{const r=await fetch(`/api/dashboard/security/${id}/${path}`,{method,headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});const b=await r.json();if(!r.ok)throw new Error(b.error||"Action failed.");await load();if(path==="dns")await loadDns(id);}catch(e){setError(e instanceof Error?e.message:"Action failed.");}finally{setBusy("");}}
async function addRecord(e:React.FormEvent){e.preventDefault();if(!form.serviceId)return;await action(form.serviceId,"dns","POST",{type:form.type,name:form.name,content:form.content,priority:form.priority?Number(form.priority):undefined,proxied:false});setForm({...form,content:""});}
return <main className="max-w-6xl space-y-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-medium">Domains</p><h1 className="text-3xl font-bold">CDN, SSL & DNS Security</h1><p className="mt-2 max-w-3xl text-sm text-ink/60">Manage Cloudflare-backed DNS, web proxying, Universal SSL and DNSSEC. Nameservers change only after you review the migrated zone and explicitly confirm cutover.</p></div><Link href="/products/security" className="btn-primary">Browse security plans</Link></div>{error&&<div className="rounded-xl border border-danger/20 bg-danger/5 p-4 text-sm text-danger">{error}</div>}{data&&!data.provider.verified&&<div className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900">Live Cloudflare controls are unavailable until the current credentials pass the provider test. {data.provider.reason||""}</div>}
{data?.services.length===0?<div className="empty-state"><h2 className="text-xl font-bold">No Cloudflare security service yet</h2><p className="mt-2 text-sm text-ink/55">Buy an active security plan and attach it to a managed domain.</p></div>:<div className="space-y-5">{data?.services.map(s=><article key={s.service_instance_id} className="card p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold">{s.domain_name}</h2><p className="text-sm text-ink/55">{s.product_name} · Zone {s.zone_status} · Service {s.service_status}</p></div><div className="flex flex-wrap gap-2"><span className={s.zone_status==="active"?"badge-success":"badge-neutral"}>{s.zone_status}</span><span className={s.proxy_enabled?"badge-success":"badge-neutral"}>CDN {s.proxy_enabled?"on":"off"}</span><span className={s.https_enforced?"badge-success":"badge-neutral"}>HTTPS {s.https_enforced?"ready":"pending"}</span><span className={s.dnssec_status==="active"?"badge-success":"badge-neutral"}>DNSSEC {s.dnssec_status}</span></div></div>
<div className="mt-5 grid gap-4 md:grid-cols-2"><div className="rounded-xl border border-border p-4"><p className="font-semibold">Assigned nameservers</p>{s.assigned_nameservers?.map(ns=><p key={ns} className="mt-1 font-mono text-xs">{ns}</p>)}<p className="mt-3 text-xs text-ink/50">Cutover: {s.cutover_status} · DNS review: {s.dns_migration_status}</p></div><div className="rounded-xl border border-border p-4"><p className="font-semibold">Paid service</p><p className="mt-2 text-sm text-ink/60">Billing: {s.billing_status||"one-time"}{s.current_period_end?` · period ends ${new Date(s.current_period_end).toLocaleDateString()}`:""}</p>{s.auto_renew!=null&&<button className="btn-secondary mt-3" disabled={busy!==""} onClick={()=>void action(s.service_instance_id,"auto-renew","PATCH",{enabled:!s.auto_renew})}>{s.auto_renew?"Turn off auto-renew":"Re-enable auto-renew"}</button>}</div></div>
<div className="mt-5 flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>loadDns(s.service_instance_id).catch(e=>setError(e.message))}>Review DNS</button>{s.cutover_status!=="ACTIVE"&&<button className="btn-primary" disabled={busy!==""} onClick={()=>{if(window.confirm("I reviewed the Cloudflare DNS records and want GetSawa to change this domain's authoritative nameservers."))void action(s.service_instance_id,"cutover","POST",{confirmed:true,recordsReviewed:true});}}>Confirm nameserver cutover</button>}{s.cutover_status==="ACTIVE"&&<button className="btn-secondary" disabled={busy!==""} onClick={()=>void action(s.service_instance_id,"proxy","PATCH",{enabled:!s.proxy_enabled})}>{s.proxy_enabled?"Disable CDN proxy":"Enable CDN proxy"}</button>}{s.cutover_status==="ACTIVE"&&s.dnssec_status!=="active"&&<button className="btn-secondary" disabled={busy!==""} onClick={()=>void action(s.service_instance_id,"dnssec")}>Enable DNSSEC</button>}</div>
{records[s.service_instance_id]&&<div className="mt-6 space-y-4"><div className="overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm"><thead className="bg-ink/5"><tr><th className="p-3">Type</th><th className="p-3">Name</th><th className="p-3">Content</th><th className="p-3">Proxy</th><th className="p-3"></th></tr></thead><tbody>{(records[s.service_instance_id]??[]).map(r=><tr key={r.id} className="border-t"><td className="p-3">{r.type}</td><td className="p-3 font-mono text-xs">{r.name}</td><td className="p-3 break-all font-mono text-xs">{r.content}</td><td className="p-3">{r.proxied?"Proxied":"DNS only"}</td><td className="p-3"><button className="text-danger" onClick={()=>{if(window.confirm("Delete this Cloudflare DNS record?"))void action(s.service_instance_id,"dns","DELETE",{id:r.id});}}>Delete</button></td></tr>)}</tbody></table></div><form onSubmit={addRecord} className="grid gap-3 rounded-xl border border-border p-4 md:grid-cols-4"><select className="input" value={form.serviceId===s.service_instance_id?form.type:"A"} onFocus={()=>setForm({...form,serviceId:s.service_instance_id})} onChange={e=>setForm({...form,serviceId:s.service_instance_id,type:e.target.value})}>{["A","AAAA","CNAME","MX","TXT","CAA"].map(t=><option key={t}>{t}</option>)}</select><input className="input" placeholder="@ or www" value={form.serviceId===s.service_instance_id?form.name:"@"} onFocus={()=>setForm({...form,serviceId:s.service_instance_id})} onChange={e=>setForm({...form,serviceId:s.service_instance_id,name:e.target.value})}/><input className="input" required placeholder="Record value" value={form.serviceId===s.service_instance_id?form.content:""} onFocus={()=>setForm({...form,serviceId:s.service_instance_id})} onChange={e=>setForm({...form,serviceId:s.service_instance_id,content:e.target.value})}/><button className="btn-primary">Add record</button></form></div>}
</article>)}</div>}</main>}
