import Link from "next/link";

const endpoints=[
 ["GET","/api/v1/domains","domains:read","List domains owned by the API-key account."],
 ["GET","/api/v1/domains/search?q=example&tlds=com,net","domains:read","Live registrar-backed availability and current protected registration price."],
 ["GET","/api/v1/domains/pricing","domains:read","Current active TLD registration/renewal/transfer pricing."],
 ["GET","/api/v1/products","products:read","Products that currently pass GetSawa's commerce-readiness gate."],
 ["GET","/api/v1/orders","orders:read","Paginated orders owned by the API-key account."],
 ["GET","/api/v1/orders/:id","orders:read","One customer-safe order record."],
 ["GET / POST","/api/v1/webhooks","webhooks:manage","List or create signed webhook subscriptions."],
 ["DELETE","/api/v1/webhooks/:id","webhooks:manage","Deactivate a webhook subscription."],
 ["POST","/api/v1/webhooks/:id/test","webhooks:manage","Send an idempotent webhook test. Requires Idempotency-Key."],
];
export default function ApiDocsPage(){return <main className="shell-container max-w-5xl py-12"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">GetSawa Developers</p><h1 className="mt-2 text-4xl font-bold">API v1</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-ink/60">Build customer-owned integrations with scoped API keys. Keys are created in the customer Developer API dashboard and sent as a Bearer token.</p></div><Link href="/dashboard/developer" className="btn-primary">Developer dashboard</Link></div>
<section className="card mt-8 p-6"><h2 className="text-xl font-bold">Authentication</h2><pre className="mt-4 overflow-x-auto rounded-xl bg-ink p-4 text-sm text-white"><code>{`Authorization: Bearer gs_live_...\nAccept: application/json`}</code></pre><p className="mt-3 text-sm text-ink/55">The raw API key is shown once. Responses include <code>X-Request-Id</code> for support and usage tracing. Rate limits are applied per API key.</p></section>
<section className="mt-8"><h2 className="text-2xl font-bold">Endpoints</h2><div className="table-shell mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b bg-paper"><th className="p-4">Method</th><th>Path</th><th>Scope</th><th>Description</th></tr></thead><tbody>{endpoints.map(([method,path,scope,description])=><tr key={path} className="border-b last:border-0"><td className="p-4 font-semibold">{method}</td><td><code>{path}</code></td><td><code>{scope}</code></td><td className="pr-4 text-ink/60">{description}</td></tr>)}</tbody></table></div></section>
<section className="mt-8 grid gap-5 lg:grid-cols-2"><div className="card p-6"><h2 className="text-xl font-bold">Webhook signature verification</h2><p className="mt-3 text-sm leading-6 text-ink/60">GetSawa signs the exact request body using HMAC-SHA256. Build the signed payload as <code>&lt;timestamp&gt;.&lt;raw-body&gt;</code>, calculate HMAC with the signing secret, and compare it to the hexadecimal value after <code>v1=</code> in <code>X-GetSawa-Signature</code>. Reject stale timestamps in your receiver.</p><div className="mt-4 space-y-1 font-mono text-xs"><p>X-GetSawa-Event-Id</p><p>X-GetSawa-Event-Type</p><p>X-GetSawa-Timestamp</p><p>X-GetSawa-Signature: v1=…</p></div></div><div className="card p-6"><h2 className="text-xl font-bold">Retries & idempotency</h2><p className="mt-3 text-sm leading-6 text-ink/60">Webhook deliveries retry with exponential backoff and stop after repeated failures. Use the event ID to make your receiver idempotent. Developer API operations that require idempotency reject a reused key when its request differs from the original request.</p><p className="mt-3 text-sm text-ink/60">For <code>POST /api/v1/webhooks/:id/test</code>, send an <code>Idempotency-Key</code> header of 8–200 safe characters.</p></div></section>
<section className="card mt-8 p-6"><h2 className="text-xl font-bold">Webhook events currently emitted</h2><div className="mt-4 grid gap-2 sm:grid-cols-2">{["order.payment_confirmed","order.provisioning","order.active","order.fulfilment_failed","renewal.invoice"].map(event=><code key={event} className="rounded-lg border border-border p-3 text-sm">{event}</code>)}</div><p className="mt-4 text-xs leading-5 text-ink/50">Only events backed by an implemented GetSawa lifecycle are documented here. Additional event families are added when their source lifecycle is production-backed.</p></section></main>}
