"use client";
import { useCallback,useEffect,useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";

type Deployment={id:string;version_id:string;status:string;created_at:string;activated_at:string};
type CustomDomain={id:string;hostname:string;status:string;certificate_id:string|null;is_primary:boolean;last_error:string|null};
type Redirect={id:string;source_path:string;target_path:string;status_code:number;enabled:boolean};
type State={project:{id:string;name:string;slug:string;status:string};deployments:Deployment[];domains:CustomDomain[];redirects:Redirect[]};
export default function PublishingPage(){const{id}=useParams<{id:string}>();const[state,setState]=useState<State|null>(null);const[domains,setDomains]=useState<Array<{id:string;name:string}>>([]);const[domainId,setDomainId]=useState("");const[hostname,setHostname]=useState("");const[replace,setReplace]=useState(false);const[source,setSource]=useState("");const[target,setTarget]=useState("");const[busy,setBusy]=useState("");const[error,setError]=useState("");
const load=useCallback(async()=>{const r=await fetch(`/api/dashboard/websites/${id}/publishing`,{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to load publishing state.");setState(b.data??b);},[id]);
useEffect(()=>{load().catch(e=>setError(e.message));fetch("/api/dashboard/domains").then(r=>r.json()).then(b=>setDomains((b.data??b).domains||[])).catch(()=>undefined);},[load]);
async function attach(){setBusy("attach");setError("");try{const r=await fetch(`/api/dashboard/websites/${id}/connect-domain`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({domainId,hostname,replaceConflictingWebRecord:replace})});const b=await r.json();if(!r.ok)throw new Error(b.error||"Could not attach custom domain.");await load();}catch(e){setError(e instanceof Error?e.message:"Could not attach custom domain.");}finally{setBusy("");}}
async function rollback(deploymentId:string){if(!window.confirm("Roll production back to this immutable version?"))return;setBusy(deploymentId);try{const r=await fetch(`/api/dashboard/websites/${id}/publishing`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"rollback",deploymentId})});const b=await r.json();if(!r.ok)throw new Error(b.error||"Rollback failed.");await load();}catch(e){setError(e instanceof Error?e.message:"Rollback failed.");}finally{setBusy("");}}
async function saveRedirect(){setBusy("redirect");try{const r=await fetch(`/api/dashboard/websites/${id}/publishing`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"redirect",sourcePath:source,targetPath:target,statusCode:301})});const b=await r.json();if(!r.ok)throw new Error(b.error||"Redirect could not be saved.");setSource("");setTarget("");await load();}catch(e){setError(e instanceof Error?e.message:"Redirect could not be saved.");}finally{setBusy("");}}
if(!state)return <p className="text-sm text-ink/60">Loading publishing…</p>;
return <main className="max-w-6xl space-y-7"><header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm text-ink/50">Website publishing</p><h1 className="text-3xl font-bold">{state.project.name}</h1><p className="mt-1 text-sm text-ink/55">Immutable production versions, Cloudflare Worker domains, automatic edge TLS and redirects.</p></div><Link className="btn-secondary" href={`/dashboard/websites/${id}`}>Back to editor</Link></header>{error&&<div className="rounded-xl border border-danger/20 bg-danger/5 p-4 text-sm text-danger">{error}</div>}
<section className="card p-6"><h2 className="text-lg font-bold">Custom domain & TLS</h2><p className="mt-1 text-sm text-ink/55">Only domains already active on GetSawa Cloudflare security can be attached. Cloudflare Worker Custom Domains create the DNS route and certificate automatically.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><select className="input" value={domainId} onChange={e=>{setDomainId(e.target.value);const d=domains.find(x=>x.id===e.target.value);if(d)setHostname(d.name);}}><option value="">Select managed domain</option>{domains.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><input className="input" value={hostname} onChange={e=>setHostname(e.target.value)} placeholder="example.com or www.example.com"/></div><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)}/>I reviewed the current apex/www web record and approve replacing it with the GetSawa Worker origin.</label><button className="btn-primary mt-4" disabled={!domainId||!hostname||busy!==""} onClick={()=>void attach()}>{busy==="attach"?"Attaching…":"Attach domain & provision TLS"}</button><div className="mt-5 space-y-2">{state.domains.map(d=><div key={d.id} className="rounded-xl border border-border p-3"><div className="flex flex-wrap justify-between gap-2"><strong>{d.hostname}</strong><span className={d.status==="ACTIVE"?"badge-success":"badge-neutral"}>{d.status}</span></div><p className="mt-1 text-xs text-ink/50">Certificate: {d.certificate_id||"pending"}{d.is_primary?" · primary":""}</p>{d.last_error&&<p className="mt-1 text-xs text-danger">{d.last_error}</p>}</div>)}</div></section>
<section className="card p-6"><h2 className="text-lg font-bold">Production deployment history</h2><p className="mt-1 text-sm text-ink/55">Every publish points production at an immutable editor version. Rollback changes the production pointer; it does not delete later versions.</p><div className="mt-4 divide-y divide-border">{state.deployments.map(d=><div key={d.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="font-semibold">{d.status} · {new Date(d.created_at).toLocaleString()}</p><p className="font-mono text-xs text-ink/45">version {d.version_id}</p></div>{d.status!=="LIVE"&&<button className="btn-secondary" disabled={busy!==""} onClick={()=>void rollback(d.id)}>Roll back here</button>}</div>)}</div></section>
<section className="card p-6"><h2 className="text-lg font-bold">Redirects</h2><div className="mt-4 grid gap-3 md:grid-cols-[1fr_1fr_auto]"><input className="input" placeholder="/old-page" value={source} onChange={e=>setSource(e.target.value)}/><input className="input" placeholder="/new-page" value={target} onChange={e=>setTarget(e.target.value)}/><button className="btn-primary" disabled={!source||!target||busy!==""} onClick={()=>void saveRedirect()}>Save 301</button></div><div className="mt-4 space-y-2">{state.redirects.map(r=><div key={r.id} className="rounded-lg border border-border p-3 text-sm"><strong>{r.source_path}</strong> → {r.target_path} <span className="text-ink/45">({r.status_code})</span></div>)}</div></section></main>}
