"use client";
import Link from "next/link";
import { useEffect,useState } from "react";

type Campaign={id:string;name:string;slug:string;status:string;channel:string;destination_path:string;clicks:number;conversions:number;value_cents:number;starts_at:string|null;ends_at:string|null};
type Commission={id:string;status:string;amountCents:number;affiliate:{user:{email:string;firstName:string;lastName:string}};order:{orderNumber:string;status:string;totalCents:number;currency:string}|null};
type Growth={campaigns:Campaign[];ads:any[];announcements:any[];sections:any[];blog:any[];commissions:Commission[];affiliateSummary:{pendingCents:number;approvedCents:number;paidCents:number;clicks:number}|null};
const money=(c:number)=>new Intl.NumberFormat(undefined,{style:"currency",currency:"USD"}).format(c/100);
export default function GrowthCenter(){const[data,setData]=useState<Growth|null>(null);const[error,setError]=useState("");const[busy,setBusy]=useState("");const[campaign,setCampaign]=useState({name:"",slug:"",channel:"LINK",destinationPath:"/",startsAt:"",endsAt:""});const[announcement,setAnnouncement]=useState({title:"",body:""});const[ad,setAd]=useState({title:"",subtitle:"",ctaLabel:"",ctaUrl:"/",priority:"10"});
async function load(){const r=await fetch("/api/admin/growth",{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to load growth center.");setData(b);}
useEffect(()=>{load().catch(e=>setError(e.message));},[]);
async function post(body:any){setBusy(body.action||"save");setError("");try{const r=await fetch("/api/admin/growth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const b=await r.json();if(!r.ok)throw new Error(b.error||"Action failed.");await load();}catch(e){setError(e instanceof Error?e.message:"Action failed.");}finally{setBusy("");}}
async function commissionAction(id:string,action:"APPROVE"|"REVERSE"){setBusy(id);try{const r=await fetch(`/api/admin/commissions/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action})});const b=await r.json();if(!r.ok)throw new Error(b.error||"Commission action failed.");await load();}catch(e){setError(e instanceof Error?e.message:"Commission action failed.");}finally{setBusy("");}}
if(!data)return <p className="text-sm text-ink/60">Loading growth center…</p>;
const totalClicks=data.campaigns.reduce((s,c)=>s+c.clicks,0),totalConversions=data.campaigns.reduce((s,c)=>s+c.conversions,0),totalValue=data.campaigns.reduce((s,c)=>s+c.value_cents,0);
return <main className="space-y-8"><header><p className="text-sm font-medium">Growth</p><h1 className="text-3xl font-bold">Growth & Content Center</h1><p className="mt-2 max-w-3xl text-sm text-ink/55">Campaign attribution, public content slots, blog publishing and affiliate economics in one operational workspace.</p></header>{error&&<div className="rounded-xl border border-danger/20 bg-danger/5 p-4 text-sm text-danger">{error}</div>}
<section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><K label="Campaign clicks" value={totalClicks}/><K label="Paid conversions" value={totalConversions}/><K label="Attributed order value" value={money(totalValue)}/><K label="Approved affiliate liability" value={money(data.affiliateSummary?.approvedCents||0)}/></section>
<section className="grid gap-5 xl:grid-cols-[1.4fr_1fr]"><div className="card p-5"><div className="flex justify-between"><h2 className="font-bold">Campaigns</h2><span className="text-xs text-ink/45">Links use /c/&lt;slug&gt;</span></div><div className="mt-4 space-y-3">{data.campaigns.map(c=><div key={c.id} className="rounded-xl border border-border p-4"><div className="flex flex-wrap justify-between gap-3"><div><strong>{c.name}</strong><p className="text-xs text-ink/45">/c/{c.slug} → {c.destination_path} · {c.channel}</p></div><select className="input max-w-36" value={c.status} disabled={busy!==""} onChange={e=>void post({action:"CAMPAIGN_STATUS",id:c.id,status:e.target.value})}>{["DRAFT","SCHEDULED","ACTIVE","PAUSED","ENDED"].map(s=><option key={s}>{s}</option>)}</select></div><div className="mt-3 flex flex-wrap gap-4 text-sm"><span>{c.clicks} clicks</span><span>{c.conversions} paid conversions</span><span>{money(c.value_cents)} attributed</span></div></div>)}</div></div>
<form className="card p-5" onSubmit={e=>{e.preventDefault();void post({action:"CREATE_CAMPAIGN",...campaign,startsAt:campaign.startsAt?new Date(campaign.startsAt).toISOString():null,endsAt:campaign.endsAt?new Date(campaign.endsAt).toISOString():null});}}><h2 className="font-bold">Create tracked campaign</h2><div className="mt-4 space-y-3"><input className="input" required placeholder="Campaign name" value={campaign.name} onChange={e=>setCampaign({...campaign,name:e.target.value})}/><input className="input" required pattern="[a-z0-9][a-z0-9-]+" placeholder="slug" value={campaign.slug} onChange={e=>setCampaign({...campaign,slug:e.target.value.toLowerCase()})}/><input className="input" required placeholder="Destination path, e.g. /domains/search" value={campaign.destinationPath} onChange={e=>setCampaign({...campaign,destinationPath:e.target.value})}/><select className="input" value={campaign.channel} onChange={e=>setCampaign({...campaign,channel:e.target.value})}>{["LINK","EMAIL","SOCIAL","PARTNER","INTERNAL"].map(x=><option key={x}>{x}</option>)}</select><div className="grid grid-cols-2 gap-2"><input className="input" type="datetime-local" value={campaign.startsAt} onChange={e=>setCampaign({...campaign,startsAt:e.target.value})}/><input className="input" type="datetime-local" value={campaign.endsAt} onChange={e=>setCampaign({...campaign,endsAt:e.target.value})}/></div><button className="btn-primary" disabled={busy!==""}>Create draft campaign</button></div></form></section>
<section className="grid gap-5 xl:grid-cols-2"><div className="card p-5"><div className="flex items-center justify-between"><h2 className="font-bold">Homepage announcements</h2><Link href="/" className="text-xs font-semibold text-brand-600">View storefront</Link></div><div className="mt-3 space-y-2">{data.announcements.slice(0,8).map(a=><div key={a.id} className="flex items-center justify-between rounded-lg border border-border p-3 text-sm"><div><strong>{a.title}</strong><p className="text-xs text-ink/45">{a.audience}</p></div><button className={a.isActive?"btn-secondary":"btn-primary"} onClick={()=>void post({action:"TOGGLE_CONTENT",kind:"ANNOUNCEMENT",id:a.id,active:!a.isActive})}>{a.isActive?"Deactivate":"Activate"}</button></div>)}</div><form className="mt-4 space-y-2" onSubmit={e=>{e.preventDefault();void post({action:"CREATE_ANNOUNCEMENT",...announcement,audience:"PUBLIC",isActive:false});}}><input className="input" required placeholder="Title" value={announcement.title} onChange={e=>setAnnouncement({...announcement,title:e.target.value})}/><textarea className="input" required rows={2} placeholder="Announcement body" value={announcement.body} onChange={e=>setAnnouncement({...announcement,body:e.target.value})}/><button className="btn-secondary">Save inactive announcement</button></form></div>
<div className="card p-5"><h2 className="font-bold">Homepage campaign banner</h2><div className="mt-3 space-y-2">{data.ads.filter(a=>a.placement==="homepage_banner").slice(0,8).map(a=><div key={a.id} className="flex items-center justify-between rounded-lg border border-border p-3 text-sm"><div><strong>{a.title}</strong><p className="text-xs text-ink/45">priority {a.priority}</p></div><button className={a.isActive?"btn-secondary":"btn-primary"} onClick={()=>void post({action:"TOGGLE_CONTENT",kind:"ADVERTISEMENT",id:a.id,active:!a.isActive})}>{a.isActive?"Deactivate":"Activate"}</button></div>)}</div><form className="mt-4 space-y-2" onSubmit={e=>{e.preventDefault();void post({action:"CREATE_AD",placement:"homepage_banner",title:ad.title,subtitle:ad.subtitle||undefined,ctaLabel:ad.ctaLabel||undefined,ctaUrl:ad.ctaUrl||undefined,priority:Number(ad.priority),isActive:false});}}><input className="input" required placeholder="Banner title" value={ad.title} onChange={e=>setAd({...ad,title:e.target.value})}/><input className="input" placeholder="Subtitle" value={ad.subtitle} onChange={e=>setAd({...ad,subtitle:e.target.value})}/><div className="grid grid-cols-2 gap-2"><input className="input" placeholder="CTA label" value={ad.ctaLabel} onChange={e=>setAd({...ad,ctaLabel:e.target.value})}/><input className="input" placeholder="/destination" value={ad.ctaUrl} onChange={e=>setAd({...ad,ctaUrl:e.target.value})}/></div><button className="btn-secondary">Save inactive banner</button></form></div></section>
<section className="card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">Affiliate commission review</h2><p className="text-xs text-ink/50">Approval revalidates the paid order; payout revalidates it again immediately before PayPal.</p></div><Link className="btn-secondary" href="/admin/affiliates">Affiliate payouts</Link></div><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-3">Affiliate</th><th className="p-3">Order</th><th className="p-3">Commission</th><th className="p-3">State</th><th className="p-3">Action</th></tr></thead><tbody>{data.commissions.map(c=><tr key={c.id} className="border-b last:border-0"><td className="p-3">{c.affiliate.user.email}</td><td className="p-3">{c.order?.orderNumber||"No order"}</td><td className="p-3">{money(c.amountCents)}</td><td className="p-3">{c.status}</td><td className="p-3"><div className="flex gap-2">{c.status==="PENDING"&&<button className="btn-primary" disabled={busy!==""} onClick={()=>void commissionAction(c.id,"APPROVE")}>Approve</button>}<button className="btn-secondary" disabled={busy!==""} onClick={()=>void commissionAction(c.id,"REVERSE")}>Reverse</button></div></td></tr>)}</tbody></table></div></section>
<section className="grid gap-4 md:grid-cols-3"><Link className="card p-5" href="/admin/blog"><strong>Blog editor</strong><p className="mt-1 text-sm text-ink/50">Draft and publish editorial content.</p></Link><Link className="card p-5" href="/admin/promotions"><strong>Promotions</strong><p className="mt-1 text-sm text-ink/50">Protected checkout promotions and offers.</p></Link><Link className="card p-5" href="/admin/coupons"><strong>Coupons</strong><p className="mt-1 text-sm text-ink/50">Customer-entered discount codes with server-side rules.</p></Link></section></main>}
function K({label,value}:{label:string;value:string|number}){return <div className="rounded-xl border border-border p-4"><p className="text-xs text-ink/50">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></div>}
