import { NextRequest } from "next/server";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { jsonError,jsonOk,handleError } from "@/lib/api";
import { getCloudflareSecurityProvider } from "@/lib/providers/security/CloudflareSecurityProvider";
import { getSecurityOperationalState } from "@/lib/security-readiness";
import { logAudit } from "@/lib/audit";
type Ctx={params:Promise<{id:string}>};const schema=z.object({action:z.enum(["SUSPEND","REACTIVATE"])});
export async function POST(req:NextRequest,{params}:Ctx){try{const admin=await requireAdmin(["SUPER_ADMIN","ADMIN","SUPPORT"]);const{id}=await params;const parsed=schema.safeParse(await req.json());if(!parsed.success)return jsonError("Invalid security service action.",422);const rows=await prisma.$queryRaw<Array<{id:string;status:string;provider_resource_id:string;zone_name:string;proxy_desired:boolean;zone_status:string}>>`SELECT psi."id",psi."status",psi."provider_resource_id",czs."zone_name",czs."proxy_desired",czs."zone_status" FROM "product_service_instances" psi JOIN "cloudflare_zone_services" czs ON czs."service_instance_id"=psi."id" WHERE psi."id"=${id} AND psi."provider_name"='cloudflare' LIMIT 1`;const service=rows[0];if(!service)return jsonError("Security service not found.",404);const state=await getSecurityOperationalState();if(!state.verified)return jsonError(state.reason||"Cloudflare provider is unavailable.",503);const provider=getCloudflareSecurityProvider();if(parsed.data.action==="SUSPEND"){await provider.setWebProxy(service.provider_resource_id,false,service.zone_name);await prisma.$executeRaw`UPDATE "product_service_instances" SET "status"='SUSPENDED',"updated_at"=CURRENT_TIMESTAMP WHERE "id"=${id}`;await prisma.$executeRaw`UPDATE "cloudflare_zone_services" SET "proxy_enabled"=FALSE,"updated_at"=CURRENT_TIMESTAMP WHERE "service_instance_id"=${id}`;}else{if(service.zone_status!=="active")return jsonError("Cloudflare zone is not active.",409);if(service.proxy_desired)await provider.setWebProxy(service.provider_resource_id,true,service.zone_name);await prisma.$executeRaw`UPDATE "product_service_instances" SET "status"='ACTIVE',"updated_at"=CURRENT_TIMESTAMP WHERE "id"=${id}`;await prisma.$executeRaw`UPDATE "cloudflare_zone_services" SET "proxy_enabled"=${service.proxy_desired},"updated_at"=CURRENT_TIMESTAMP WHERE "service_instance_id"=${id}`;}await logAudit({actorId:admin.id,action:parsed.data.action==="SUSPEND"?"security.admin_suspended":"security.admin_reactivated",resource:"security_service",resourceId:id});return jsonOk({status:parsed.data.action==="SUSPEND"?"SUSPENDED":"ACTIVE"});}catch(error){return handleError(error);}}
