"use client";
import { useEffect,useState } from "react";

interface User { email:string;firstName:string;lastName:string;phone:string|null;company:string|null;country:string|null;mfaEnabled:boolean;createdAt:string; }
interface Session {id:string;ipAddress:string|null;userAgent:string|null;createdAt:string;expiresAt:string;isCurrent:boolean}
interface Notification {id:string;title:string;body:string;type:string;readAt:string|null;createdAt:string}

export default function SettingsPage(){
 const [user,setUser]=useState<User|null>(null); const [sessions,setSessions]=useState<Session[]>([]); const [notifications,setNotifications]=useState<Notification[]>([]); const [unread,setUnread]=useState(0); const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false); const [form,setForm]=useState({firstName:"",lastName:"",phone:"",company:"",country:""}); const [password,setPassword]=useState({currentPassword:"",newPassword:""});
 async function load(){const [p,s,n]=await Promise.all([fetch("/api/dashboard/profile"),fetch("/api/dashboard/security/sessions"),fetch("/api/dashboard/notifications")]);const pd=await p.json();const sd=await s.json();const nd=await n.json();if(pd.user){setUser(pd.user);setForm({firstName:pd.user.firstName,lastName:pd.user.lastName,phone:pd.user.phone||"",company:pd.user.company||"",country:pd.user.country||""});}setSessions(sd.sessions||[]);setNotifications(nd.notifications||[]);setUnread(nd.unreadCount||0);}
 useEffect(()=>{load();},[]);
 async function saveProfile(e:React.FormEvent){e.preventDefault();setSaving(true);setMessage("");try{const r=await fetch("/api/dashboard/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not save profile");setUser(u=>u?{...u,...d.user}:u);setMessage("Profile updated.");}catch(e){setMessage(e instanceof Error?e.message:"Could not save profile.");}finally{setSaving(false);}}
 async function changePassword(e:React.FormEvent){e.preventDefault();setSaving(true);setMessage("");try{const r=await fetch("/api/dashboard/security/password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(password)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not change password");setPassword({currentPassword:"",newPassword:""});setMessage("Password changed. All existing sessions were signed out. Please sign in again.");}catch(e){setMessage(e instanceof Error?e.message:"Could not change password.");}finally{setSaving(false);}}
 async function revoke(id:string){await fetch("/api/dashboard/security/sessions",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId:id})});await load();}
 async function revokeAll(){await fetch("/api/dashboard/security/sessions",{method:"PATCH"});window.location.href="/login";}
 async function mark(id?:string){await fetch("/api/dashboard/notifications",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(id?{id}:{all:true})});await load();}
 if(!user)return <p className="text-ink/60">Loading…</p>;
 return <div className="max-w-4xl space-y-8"><div><h1 className="text-2xl font-semibold">Account & Security</h1><p className="mt-1 text-sm text-ink/60">Manage your identity, password, active sessions and account notifications.</p></div>{message&&<div className="card p-4 text-sm">{message}</div>}
 <section><h2 className="text-lg font-semibold">Profile</h2><form onSubmit={saveProfile} className="card mt-3 grid gap-4 p-6 sm:grid-cols-2">{([['firstName','First name'],['lastName','Last name'],['phone','Phone'],['company','Company'],['country','Country']] as const).map(([k,l])=><div key={k}><label className="label">{l}</label><input className="input" value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></div>)}<div className="sm:col-span-2"><button disabled={saving} className="btn-primary">{saving?"Saving…":"Save profile"}</button></div></form></section>
 <section><h2 className="text-lg font-semibold">Password</h2><form onSubmit={changePassword} className="card mt-3 space-y-4 p-6"><div><label className="label">Current password</label><input className="input" type="password" required value={password.currentPassword} onChange={e=>setPassword({...password,currentPassword:e.target.value})}/></div><div><label className="label">New password</label><input className="input" type="password" minLength={10} required value={password.newPassword} onChange={e=>setPassword({...password,newPassword:e.target.value})}/><p className="mt-1 text-xs text-ink/50">Use at least 10 characters. Changing it signs out every active session.</p></div><button disabled={saving} className="btn-primary">Change password</button></form></section>
 <section><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Active sessions</h2><p className="text-sm text-ink/60">Review where your account is signed in.</p></div><button onClick={revokeAll} className="btn-danger">Sign out everywhere</button></div><div className="card mt-3 divide-y divide-border">{sessions.map(s=><div key={s.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="font-medium">{s.isCurrent?"This device":"Active session"}{s.ipAddress&&<span className="ml-2 text-xs text-ink/50">{s.ipAddress}</span>}</p><p className="text-xs text-ink/50">{s.userAgent||"Unknown browser"} · signed in {new Date(s.createdAt).toLocaleString()}</p></div>{s.isCurrent?<span className="badge-success">Current</span>:<button onClick={()=>revoke(s.id)} className="btn-secondary text-sm">Revoke</button>}</div>)}{sessions.length===0&&<p className="p-5 text-sm text-ink/60">No active sessions.</p>}</div></section>
 <section><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Notifications {unread>0&&<span className="badge-warning ml-2">{unread} unread</span>}</h2><p className="text-sm text-ink/60">Important account, domain and billing events.</p></div>{unread>0&&<button onClick={()=>mark()} className="btn-secondary">Mark all read</button>}</div><div className="card mt-3 divide-y divide-border">{notifications.map(n=><button key={n.id} onClick={()=>mark(n.id)} className={`block w-full p-4 text-left hover:bg-paper ${n.readAt?"opacity-60":""}`}><div className="flex justify-between gap-4"><span className="font-medium">{n.title}</span><span className="text-xs text-ink/40">{new Date(n.createdAt).toLocaleString()}</span></div><p className="mt-1 text-sm text-ink/60">{n.body}</p></button>)}{notifications.length===0&&<p className="p-5 text-sm text-ink/60">No notifications.</p>}</div></section>
 <section className="card p-5"><h2 className="font-semibold">Two-factor authentication</h2><p className="mt-1 text-sm text-ink/60">Status: <strong>{user.mfaEnabled?"Enabled":"Not enabled"}</strong>. Use the existing MFA enrollment controls to change this setting.</p></section>
 </div>;
}
