"use client";

import { useEffect, useState } from "react";

function money(cents:number,currency:string){return new Intl.NumberFormat(undefined,{style:"currency",currency}).format(cents/100);}
function date(v:string){return new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));}

export default function AdminBillingPage(){const [data,setData]=useState<any>(null);const [error,setError]=useState("");
 useEffect(()=>{fetch("/api/admin/billing",{cache:"no-store"}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to load billing.");setData(b.data??b);}).catch(e=>setError(e instanceof Error?e.message:"Unable to load billing."));},[]);
 if(error)return <div className="rounded-xl border p-6">{error}</div>;if(!data)return <div>Loading billing operations...</div>;
 return <div className="space-y-8"><header><p className="text-sm font-medium text-ink/50">Operations</p><h1 className="text-3xl font-bold">Billing & renewals</h1><p className="mt-2 text-sm text-ink/60">Monitor recurring services, renewal invoices and payment exceptions.</p></header>
 <div className="grid gap-4 md:grid-cols-3"><div className="rounded-xl border bg-surface p-5"><p className="text-sm text-ink/50">Subscriptions</p><p className="mt-1 text-2xl font-bold">{data.subscriptions.length}</p></div><div className="rounded-xl border bg-surface p-5"><p className="text-sm text-ink/50">Pending payment orders</p><p className="mt-1 text-2xl font-bold">{data.pendingOrders}</p></div><div className="rounded-xl border bg-surface p-5"><p className="text-sm text-ink/50">Failed payments</p><p className="mt-1 text-2xl font-bold">{data.failedPayments}</p></div></div>
 <section className="space-y-3"><h2 className="text-xl font-semibold">Renewal queue</h2><div className="overflow-x-auto rounded-xl border bg-surface"><table className="w-full text-left text-sm"><thead className="border-b bg-paper"><tr><th className="p-4">Customer</th><th className="p-4">Domain</th><th className="p-4">Status</th><th className="p-4">Period end</th><th className="p-4">Scheduled</th></tr></thead><tbody>{data.renewals.length===0?<tr><td colSpan={5} className="p-6 text-ink/50">No renewal attempts.</td></tr>:data.renewals.map((r:any)=><tr key={r.id} className="border-b last:border-0"><td className="p-4">{r.customer_email}</td><td className="p-4 font-medium">{r.domain_name??"—"}</td><td className="p-4">{r.status}</td><td className="p-4">{date(r.period_end)}</td><td className="p-4">{date(r.scheduled_at)}</td></tr>)}</tbody></table></div></section>
 <section className="space-y-3"><h2 className="text-xl font-semibold">Recurring services</h2><div className="overflow-x-auto rounded-xl border bg-surface"><table className="w-full text-left text-sm"><thead className="border-b bg-paper"><tr><th className="p-4">Customer</th><th className="p-4">Domain</th><th className="p-4">Amount</th><th className="p-4">Next billing</th><th className="p-4">Auto-renew</th></tr></thead><tbody>{data.subscriptions.map((s:any)=><tr key={s.id} className="border-b last:border-0"><td className="p-4">{s.customer_email}</td><td className="p-4 font-medium">{s.domain_name??"—"}</td><td className="p-4">{money(Number(s.amount_cents),s.currency)}</td><td className="p-4">{date(s.next_billing_at)}</td><td className="p-4">{s.auto_renew?"Yes":"No"}</td></tr>)}</tbody></table></div></section>
 </div>;
}
