"use client";

import { useEffect, useMemo, useState } from "react";

function money(cents:number,currency="USD"){return new Intl.NumberFormat(undefined,{style:"currency",currency}).format(cents/100);}
function date(v:string){return new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));}

export default function AdminBillingPage(){const [data,setData]=useState<any>(null);const [error,setError]=useState("");
 useEffect(()=>{fetch("/api/admin/billing",{cache:"no-store"}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to load billing.");setData(b.data??b);}).catch(e=>setError(e instanceof Error?e.message:"Unable to load billing."));},[]);
 const finance=useMemo(()=>{const events=data?.finance?.events??[];const byType=new Map(events.map((e:any)=>[e.eventType,e]));const captured:any=byType.get("PAYMENT_CAPTURED");const refunded:any=byType.get("PAYMENT_REFUNDED");return {gross:Number(captured?.grossCents??0),fees:Number(captured?.providerFeeCents??0)+Number(refunded?.providerFeeCents??0),refunds:Number(refunded?.grossCents??0),net:events.reduce((sum:number,e:any)=>sum+Number(e.netCents??0),0)};},[data]);
 if(error)return <div className="rounded-xl border p-6">{error}</div>;if(!data)return <div>Loading billing operations…</div>;
 return <div className="space-y-8"><header><p className="text-sm font-medium text-ink/50">Operations</p><h1 className="text-3xl font-bold">Billing & finance</h1><p className="mt-2 max-w-3xl text-sm text-ink/60">Monitor settlement truth, renewal invoices, payment exceptions, provider fees and customer credit exposure. Financial events are idempotent across browser capture, webhooks and reconciliation.</p></header>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Gross captured" value={money(finance.gross)}/><Metric label="Refunded" value={money(finance.refunds)}/><Metric label="Provider fees" value={money(finance.fees)}/><Metric label="Net settlement" value={money(finance.net)}/></div>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Subscriptions" value={String(data.subscriptions.length)}/><Metric label="Pending payment orders" value={String(data.pendingOrders)}/><Metric label="Failed payments" value={String(data.failedPayments)}/><Metric label="Disputed payments" value={String(data.disputedPayments)}/></div>
 <div className="rounded-xl border bg-surface p-5"><p className="text-sm text-ink/50">Outstanding customer credit liability</p><p className="mt-1 text-2xl font-bold">{money(Number(data.creditOutstandingCents??0))}</p><p className="mt-1 text-xs text-ink/50">Sum of issued credit adjustments currently held on customer accounts.</p></div>
 <section className="space-y-3"><div><h2 className="text-xl font-semibold">Renewal queue</h2><p className="text-sm text-ink/50">Renewal invoice prices are refreshed from the registrar before payment handoff.</p></div><div className="overflow-x-auto rounded-xl border bg-surface"><table className="w-full text-left text-sm"><thead className="border-b bg-paper"><tr><th className="p-4">Customer</th><th className="p-4">Domain</th><th className="p-4">Status</th><th className="p-4">Period end</th><th className="p-4">Scheduled</th></tr></thead><tbody>{data.renewals.length===0?<tr><td colSpan={5} className="p-6 text-ink/50">No renewal attempts.</td></tr>:data.renewals.map((r:any)=><tr key={r.id} className="border-b last:border-0"><td className="p-4">{r.customer_email}</td><td className="p-4 font-medium">{r.domain_name??"—"}</td><td className="p-4">{r.status}</td><td className="p-4">{date(r.period_end)}</td><td className="p-4">{date(r.scheduled_at)}</td></tr>)}</tbody></table></div></section>
 <section className="space-y-3"><h2 className="text-xl font-semibold">Recurring services</h2><div className="overflow-x-auto rounded-xl border bg-surface"><table className="w-full text-left text-sm"><thead className="border-b bg-paper"><tr><th className="p-4">Customer</th><th className="p-4">Domain</th><th className="p-4">Estimated amount</th><th className="p-4">Next invoice check</th><th className="p-4">Automation</th></tr></thead><tbody>{data.subscriptions.map((s:any)=><tr key={s.id} className="border-b last:border-0"><td className="p-4">{s.customer_email}</td><td className="p-4 font-medium">{s.domain_name??"—"}</td><td className="p-4">{money(Number(s.amount_cents),s.currency)}<div className="text-xs text-ink/50">Re-priced before payment</div></td><td className="p-4">{date(s.next_billing_at)}</td><td className="p-4">{s.auto_renew?"Enabled":"Disabled"}</td></tr>)}</tbody></table></div></section>
 </div>;
}

function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl border bg-surface p-5"><p className="text-sm text-ink/50">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div>}
